In [1]:
import numpy as np

In [11]:
ar2 = np.array([[85,90,78],[92,88,95],[76,95,85],[90,85,92],[88,76,89]])



In [12]:
ar2

array([[85, 90, 78],
       [92, 88, 95],
       [76, 95, 85],
       [90, 85, 92],
       [88, 76, 89]])

In [13]:


np.mean(ar2,axis=1)

array([84.33333333, 91.66666667, 85.33333333, 89.        , 84.33333333])

In [14]:
np.median(ar2, axis=0)

array([88., 88., 89.])

In [25]:
np.argmax(ar2,axis=1)

array([1, 2, 1, 2, 2])

In [17]:
np.max(ar2,axis=0)

array([92, 95, 95])

In [18]:
np.min(ar2,axis=0)

array([76, 76, 78])

In [26]:
np.reshape(ar2,(3,5))

array([[85, 90, 78, 92, 88],
       [95, 76, 95, 85, 90],
       [85, 92, 88, 76, 89]])

In [27]:
np.sort(ar2,axis=0)

array([[76, 76, 78],
       [85, 85, 85],
       [88, 88, 89],
       [90, 90, 92],
       [92, 95, 95]])

In [28]:
np.sort(ar2,axis=1)


array([[78, 85, 90],
       [88, 92, 95],
       [76, 85, 95],
       [85, 90, 92],
       [76, 88, 89]])

In [34]:
np.argsort(ar2,axis=0)

array([[2, 4, 0],
       [0, 3, 2],
       [4, 1, 4],
       [3, 0, 3],
       [1, 2, 1]])

In [35]:
'''
syntax
input output error
compile time error
runtime error   '''

'\nsyntax\ninput output error\ncompile time error\nruntime error   '

In [62]:
sum=np.sum(ar2,axis=1)
print(max(sum))
index= np.argmax(sum)
high= ar2[index]

print(high)









275
[92 88 95]
